[tool.poetry]
name = "firstusepyqt"
version = "0.1.0"
description = ""
authors = ["Nuri <nuri.bokieva@emergingtravel.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyqt6 = "^6.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
